In [1]:
import numpy as np

#Optimal maintenance problem
p = np.array([[(0,0)]*2 for i in range(4)])
#p[s,a]=(r,s')
p[(0,1)]=(-10,0)
p[(1,1)]=(-10,0)
p[(1,0)]=(-1,1)
p[(0,0)]=(0,0)
gamma = 0.9

def epsilon_greedy_pi(Q,state,epsilon):
    if np.random.random() < epsilon:
        return np.random.choice(2)
    else:
        return Q[state,:].argmax()

def take_action(state_action):
    return p[state_action]

def dyna(n, n_timestep, epsilon, alpha, gamma):
    Q = np.ones((2,2))
    model = np.array([[(0,0)]*2 for i in range(4)])
    
    observed_s_a = {}
    
    for i in range(n_timestep):
        state = np.random.randint(2)
        action = epsilon_greedy_pi(Q,state,epsilon)
        
        if state in observed_s_a:
            observed_s_a[state].append(action)
        else:
            observed_s_a[state] = [action]

        reward, next_state = take_action((state,action))

        Q[state,action] += alpha * (reward + gamma * Q[next_state,:].argmax() - Q[state,action])
        model[state,action] = [reward,next_state]
        
        for j in range(n):
            state = np.random.choice(list(observed_s_a.keys()))
            action = np.random.choice(observed_s_a[state])
            
            reward, next_state = model[state,action]
            Q[state,action] += alpha * (reward + gamma * Q[next_state,:].argmax() - Q[state,action])
    
    return Q, model

In [2]:
Q, model = dyna(n=5, n_timestep=10, epsilon=0.1, alpha=0.1, gamma=0.9)

In [3]:
print(Q)

[[ 0.05814974 -6.51670238]
 [-0.25572219 -4.154149  ]]


In [4]:
print(model)

[[[  0   0]
  [-10   0]]

 [[ -1   1]
  [-10   0]]

 [[  0   0]
  [  0   0]]

 [[  0   0]
  [  0   0]]]


In [5]:
model == p

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])